### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by flipdeezy** [Dexesttp/hkxpack#14]
getting a strange error when trying to unpack multiple files in a directory. Using single file names works fine though. Using the latest version of JRE 102 on windows 10. The source folder is on my desktop 

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at com.dexesttp.hkxpack.cli.commands.Command_unpack.extractFileName(Command_unpack.java:39)
        at com.dexesttp.hkxpack.cli.commands.Command_IO.execute_single(Command_IO.java:70)
        at com.dexesttp.hkxpack.cli.commands.Command_IO.execute(Command_IO.java:59)
        at com.dexesttp.hkxpack.cli.ConsoleView.main(ConsoleView.java:17)

**Comment by Dexesttp** [comment]
Although I don't know why the error happens exactly, it means that a file without an extension was trying to be converted.

As I said, it shouldn't happen - by that I mean a file without extension should never be matched for conversion in the first place.

If you could give me a list of every file you have in this directory, that would be a good start to debug it. I'll try to search for a possible cause on my side too. I'll also improve the error message to include the file name just in case.

**Comment by flipdeezy** [comment]
I see. Oddly, I only had a single file on the folder. It was a vanilla .hkx file

The folder structure is set up like so

Desktop/HKXMainFolder/Havok/Idle.hkx

I also have an out folder in the main directory

Desktop/HKXMainFolder/Out/Havok

Finbaly, not sure if it helps,  but this same setup used to work perfectly on my windows 7 PC. My is crashed and I reinstalled Windows 10 instead. Then re-download the jar files and setup the fipenstructure exactly the same way, and now for some reason the batch convert doesn't work.

**Comment by flipdeezy** [comment]
Apologies for the typos, responding from my phone

**Comment by flipdeezy** [comment]
Oh and I should add that the exact same file converts fine when I use the single file conversion and just add the exact filename

**Comment by Dexesttp** [comment]
Hmm... Weird. I think there's an hidden file somewhere that somehow passes the detection phase.

Could you try with the version I attached ? It has the latest error message and should allow you to see why the error happens.

[hkxpack-cli.zip](https://github.com/Dexesttp/hkxpack/files/517872/hkxpack-cli.zip)

**Comment by flipdeezy** [comment]
Yes will do right now

**Comment by flipdeezy** [comment]
hmm...now im not getting an error at all...BUT there is no file in he output folder

**Comment by flipdeezy** [comment]
I tired adding the -V modifier and still got nothing, no error no report etc. 

I also tried adding the -o modifier and specifying a specific output folder like so 

java -jar hkxpack-cli.jar unpack C:\Users\Admins - Desktop\Desktop\hkx\Havok -o C:\Users\Admins - Desktop\Desktop\hkx\out\Havok

**Comment by flipdeezy** [comment]
Wonder if it could be because my user profile is "Admins - Desktop"

Maybe it doesn't like the hyphen or the spaces?

**Comment by Dexesttp** [comment]
Nothing is really weird though, you should at least get a message with the number of files detected.

Does the single-file command still works ?

Maybe that's the reason, i'll try some things to see if that's it.

**Comment by flipdeezy** [comment]
yes the single file command does still work. The only difference is that the single file needs to be in the same folder as the jar file, where the multi file command in the past didn't need to be in the same directory. I can try to see if the putting the file in the main directory with the jar files and using the multi-file command helps.

**Comment by flipdeezy** [comment]
unfortunately its the same result when placing the file in the main directory as well.

the file is is C:\Users\Admins - Desktop\Desktop\hkx

and I am using the following command

java -jar hkxpack-cli.jar unpack C:\Users\Admins - Desktop\Desktop\hkx\Havok

just as a sanity check

by the way, thank you so much for your help on this. I really appreciate you being so responsive you are awesome!

**Comment by Dexesttp** [comment]
No problem :)

Hmm... You'll need some quotes around your path because it has spaces, so like `java -jar hkxpack-cli.jar unpack "C:\Users\Admins - Desktop\Desktop\hkx\Havok"`.

I've managed to get some errors on my side with this kind of syntax, and I'm doing some tests.

**Comment by flipdeezy** [comment]
AHH that did it!

Is that syntax common knowledge? I had no idea that was the case. Im sorry if it is...oh boy that is on me

**Comment by Dexesttp** [comment]
It's not that common, but it's good to know :)

Well, if that solved the problem then I guess that's OK :) At least now the error messages should be a bit more explicit.

**Comment by flipdeezy** [comment]
Well when i didnt have the quotes it didnt seem to give me any message at all.

With the quotes it displays [INFO] Detected 1 files to handle.

So its working perfectly now. I'm sad to say I regularly use command line in my day job, and I had no idea adding quotes to a path with spaces in it was necessary. I feel pretty dumb lol

Maybe you could add it to he instructions on the main page for dummies like me, although I prob should have known this.

thanks again for all of your help!

**Comment by Dexesttp** [comment]
Nice to know it's working ! I'll add a note to the main page.

No problem, that was fun to do :)

**Comment by flipdeezy** [comment]
Thanks again :)
