### ISSUE TITLE
Big-Endian Support

### ISSUE THREAD

**Issue by PredatorCZ** [Dexesttp/hkxpack#18]
Hello, I think you're able to implement BigEndian Support for Binary hkx files.
To resolve endianness of file, there is flag in header: HeaderDescriptor::extras:: second element, 1 means Little Endian, 0 means Big Endian. Probably the best solution would be creating global bool variable, and adding byteswap to byteutils.
Thank you.

**Comment by abso1utezer0** [comment]
Is this completed? It is still throwing errors for both Epic Mickey games.
