### ISSUE TITLE
Where to locate classXML files in Fallout 4.

### ISSUE THREAD

**Issue by ZBroadcast02** [Dexesttp/hkxpack#29]
I purchased Fallout 4 on Steam, however I have been unable to find any "classXML" files in the game's folders to use in order to get the hkxpack tool to work. Any way I could find them?

**Comment by Dexesttp** [comment]
Hello,

Obtaining the classXML files is out of scope for this project, as indicated in the README.

Given your question, you probably just want to use the tool and are not planning to tinker with the code. There is provided downloads for working versions of hkxpack - you can find the latest release [here](https://github.com/Dexesttp/hkxpack/releases/tag/v0.1.6-beta).
